# Generated by Django 4.2.7 on 2024-07-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('course_duration', models.IntegerField(max_length=10)),
                ('seat', models.IntegerField()),
            ],
        ),
    ]
